title: openbookstudio
url: https://openbookstudio.github.io/
baseurl: 

author: Eliana Yeom, pleasing_aroma
description: Following the path of the light.

include: ['_pages']

collections_dir: series

collections:
  home:
    output: true
  pondi:
    output: true
  kochi:
    output: true
  rj_women:
    output: true
  venice:
    output: true
  chinatown:
    output: true
  rimi:
    output: true
  london:
    output: true
  mumbai:
    output: true
  cn_fishnet:
    output: true
  market:
    output: 
  bastilleday:
    output: true
  kathakali:
    output: true 

markdown: kramdown
kramdown:
  input: GFM
